# Generated by Django 4.1 on 2022-09-07 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerOrderDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderItem', models.CharField(choices=[('psn', 'PSN'), ('client', 'CLIENT')], default='client', max_length=6, verbose_name='Item')),
                ('quantity', models.PositiveIntegerField(verbose_name='Quantity')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerOrderEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customerName', models.CharField(max_length=300, verbose_name='Customer Name')),
                ('entryDate', models.DateTimeField(verbose_name='date added')),
                ('customerOrder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customerdatabase.customerorderdetails')),
            ],
        ),
    ]
